[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
members = ["zomes/coordinator/*", "zomes/integrity/*"]
resolver = "2"

[workspace.dependencies]
hdi = "0.7.0-dev"
hdk = "0.6.0-dev"
holochain_serialized_bytes = "*"
serde = "1"

